[package]
name = "rust_lib_shell_assistant"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.6.0"
sysinfo = "0.33.1"
walkdir = "2.5.0"
plist = "1.7.0"
anyhow = "1"
