// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'entity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_latest_release_info`

Future<void> checkUpdate(
        {required String curVersion,
        required FutureOr<void> Function(ReleaseInfo?) callback}) =>
    RustLib.instance.api
        .crateApiUpdaterCheckUpdate(curVersion: curVersion, callback: callback);
